version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - '33066:3306'
    volumes:
      - ./mysql/.data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default_authentication_plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    networks:
      - aapa-network
    container_name: mysql

networks:
  aapa-network:
